### ISSUE TITLE
RIP

### ISSUE THREAD

**Issue by parkerlreed** [eyenx/yify.py#7]
https://torrentfreak.com/yify-yts-shuts-down-the-end-of-a-piracy-icon-151030/

Well that was fun while it lasted.

**Comment by eyenx** [comment]
:-(

**Comment by parkerlreed** [comment]
:,(

**Comment by josefson** [comment]
Its back in a different server: yts.ag, can't it be used?

**Comment by eyenx** [comment]
It's not the real deal.

https://torrentfreak.com/yts-ag-wants-to-be-the-new-yify-on-popular-torrent-sites-151113/
